### ISSUE TITLE
Shall we retire this repo?

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-gitian#2] opened 2020-01-08 13:32 UTC
@kayabaNerve - you started the initiative, what are your thoughts about it?

**Comment by kayabaNerve** [comment] 2020-01-08 19:26
Gitian is still the best option for reproducible builds.

The reason I stopped working on this is because when I worked on this months ago, I couldn't get Gitian to use the needed environment variables for some reason. My plan was to complete Tauri's Gitian setup when I did one for my own work. The one for my own work has yet to happen though, so neither has Tauri's.

I'll try again to get a working setup within the next week. If I get a working setup, I'll complete the scripts for Tauri. If I can't, we might as well for now.

**Comment by kayabaNerve** [comment] 2020-01-15 09:41
I discussed this privately with @nothingismagick, yet my hard drive died. Due to that, I'm waiting to close this repository until I can actually attempt to setup a Gitian environment again.

**Comment by nothingismagick** [comment] 2020-01-15 11:18
Yeah - well, in the meantime it would be excellent if you could pimp out the readme with a little more information about the status / approach / goals / challenges etc.

**Closed** 2020-01-17 13:34 UTC
